services:
  nats:
    image: nats:2.10-alpine
    command: ["-js"]   # JetStream habilitado por si lo usas en el futuro
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Descomenta si tienes GPU NVIDIA:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]

volumes:
  ollama_data:
